# TODO:
#   Change the coordinates from pixel/pixel to u/v.
#   Make this a YAML file.

base_id = 'BASE_ID'
coords  = 'COORDS'
name    = 'NAME'
active  = 'ACTIVE'

bases = [{base_id: 1,
          coords: (4318,  828),
          name: "Hamburg",
          active: False,
         },
         {base_id: 2,
          coords: (4197,  880),
          name: "Antwerpen",
          active: False, # base culling
         },
         {base_id: 3,
          coords: (4286,  906),
          name: "Frankfurt",
          active: True,
         },
         {base_id: 4,
          coords: (4094,  875),
          name: "London",
          active: True,
         },
         {base_id: 5,
          coords: (4095,  885),
          name: "Saint Hill Green",
          active: False, # redacted
         },
         {base_id: 6,
          coords: (3992,  749),
          name: "Boleskine House",
          active: False, # too close to Glasgow
         },
         {base_id: 7,
          coords: (3999,  777),
          name: "Glasgow",
          active: False, # base culling
         },
         {base_id: 8,
          coords: (4214,  862),
          name: "Utrecht",
          active: False, # base culling
         },
         {base_id: 9,
          coords: (3888, 1166),
          name: "Lisbon",
          active: True,
         },
         {base_id: 10,
          coords: (4400,  852),
          name: "Berlin",
          active: False, # base culling
         },
         {base_id: 11,
          coords: (4380,  780),
          name: "Copenhagen",
          active: False, # base culling
         },
         {base_id: 12,
          coords: (4380, 1094),
          name: "Rome",
          active: True,
         },
         {base_id: 13,
          coords: (3903,  867),
          name: "Cork",
          active: False, # base culling
         },
         {base_id: 14,
          coords: (3598,  589),
          name: "Reykjavik",
          active: True,
         },
         {base_id: 15,
          coords: (4887, 1317),
          name: "Tel Aviv",
          active: True,
         },
         {base_id: 16,
          coords: (4636, 1183),
          name: "Athens",
          active: True,
         },
         {base_id: 17,
          coords: (4144, 1104),
          name: "Barcelona",
          active: True,
         },
         {base_id: 18,
          coords: (4012, 1127),
          name: "Madrid",
          active: False, # base culling
         },
         {base_id: 19,
          coords: (4082, 1027),
          name: "Bordeaux",
          active: False, # base culling
         },
         {base_id: 20,
          coords: (4290,  969),
          name: "Zurich",
          active: False, # too close to Liechtenstein
         },
         {base_id: 21,
          coords: (4313,  974),
          name: "Liechtenstein",
          active: False, # base culling
         },
         {base_id: 22,
          coords: (4503,  696),
          name: "Stockholm",
          active: True,
         },
         {base_id: 23,
          coords: (3953,  834),
          name: "Dublin",
          active: True,
         },
         {base_id: 24,
          coords: (4574,  859),
          name: "Warsaw",
          active: False, # base culling
         },
         {base_id: 25,
          coords: (4550,  909),
          name: "Krakow",
          active: True,
         },
         {base_id: 26,
          coords: (4723,  821),
          name: "Minsk",
          active: False, # base culling
         },
         {base_id: 27,
          coords: (4468,  951),
          name: "Vienna",
          active: False, # base culling
         },
         {base_id: 28,
          coords: (4531,  968),
          name: "Budapest",
          active: False, # base culling
         },
         {base_id: 29,
          coords: (4689, 1036),
          name: "Bucharest",
          active: False, # base culling
         },
         {base_id: 30,
          coords: (4794,  990),
          name: "Odessa",
          active: True,
         },
         {base_id: 31,
          coords: (4754, 1113),
          name: "Istanbul",
          active: True,
         },
         {base_id: 32,
          coords: (3958, 1252),
          name: "Tangier",
          active: True,
         },
         {base_id: 33,
          coords: (4735, 2643),
          name: "Johannesburg",
          active: True,
         },
         {base_id: 34,
          coords: (4090, 1920),
          name: "Accra",
          active: True,
         },
         {base_id: 35,
          coords: (4807, 1364),
          name: "Cairo",
          active: True,
         },
         {base_id: 36,
          coords: (4988, 2202),
          name: "Zanzibar",
          active: True,
         },
         {base_id: 37,
          coords: (4835, 1692),
          name: "Khartoum",
          active: True,
         },
         {base_id: 38,
          coords: (4518, 2820),
          name: "Cape Town",
          active: True,
         },
         {base_id: 39,
          coords: (4443, 2146),
          name: "Kinshasa",
          active: True,
         },
         {base_id: 40,
          coords: (4904, 1277),
          name: "Beirut",
          active: True,
         },
         {base_id: 41,
          coords: (6504, 1569),
          name: "Hanoi",
          active: True,
         },
         {base_id: 42,
          coords: (6526, 2189),
          name: "Jakarta",
          active: True,
         },
         {base_id: 43,
          coords: (6459, 2016),
          name: "Singapore",
          active: True,
         },
         {base_id: 44,
          coords: (6985, 1193),
          name: "Seoul",
          active: True,
         },
         {base_id: 45,
          coords: (5353, 1472),
          name: "Dubai",
          active: True,
         },
         {base_id: 46,
          coords: (6849, 1715),
          name: "Manila",
          active: True,
         },
         {base_id: 47,
          coords: (5621, 1481),
          name: "Karachi",
          active: True,
         },
         {base_id: 48,
          coords: (5787, 1330),
          name: "Lahore",
          active: True,
         },
         {base_id: 49,
          coords: (5619, 1145),
          name: "Samarkand",
          active: True,
         },
         {base_id: 50,
          coords: (5266, 1236),
          name: "Tehran",
          active: True,
         },
         {base_id: 51,
          coords: (5759,  914),
          name: "Astana",
          active: True,
         },
         {base_id: 52,
          coords: (6528,  957),
          name: "Ulaanbaatar",
          active: True,
         },
         {base_id: 53,
          coords: (6861, 1478),
          name: "Taipeh",
          active: True,
         },
         {base_id: 54,
          coords: (6685, 1530),
          name: "Hong Kong",
          active: True,
         },
         {base_id: 55,
          coords: (6744, 1139),
          name: "Beijing",
          active: True,
         },
         {base_id: 56,
          coords: (6859, 1337),
          name: "Shanghai",
          active: True,
         },
         {base_id: 57,
          coords: (6673, 1521),
          name: "Guangzhou",
          active: False, # too close to Hong Kong
         },
         {base_id: 58,
          coords: (6464, 1350),
          name: "Chengdu",
          active: True,
         },
         {base_id: 59,
          coords: (6575, 1268),
          name: "Xi'an",
          active: True,
         },
         {base_id: 60,
          coords: (6977, 1007),
          name: "Harbin",
          active: True,
         },
         {base_id: 61,
          coords: (4951, 779),
          name: "Moscow",
          active: True,
         },
         {base_id: 62,
          coords: (4784, 685),
          name: "Saint Petersburg",
          active: True,
         },
         {base_id: 63,
          coords: (5111, 940),
          name: "Volgograd",
          active: True,
         },
         {base_id: 64,
          coords: (5982, 796),
          name: "Novosibirsk",
          active: True,
         },
         {base_id: 65,
          coords: (6469, 858),
          name: "Irkutsk",
          active: True,
         },
         {base_id: 66,
          coords: (4849, 478),
          name: "Murmansk",
          active: True,
         },
         {base_id: 67,
          coords: (5111, 940),
          name: "Volgograd",
          active: True,
         },
         {base_id: 68,
          coords: (5982, 796),
          name: "Novosibirsk",
          active: True,
         },
         {base_id: 69,
          coords: (5493, 792),
          name: "Chelyabinsk",
          active: True,
         },
         {base_id: 70,
          coords: (5094, 766),
          name: "Nizny Novgorod",
          active: True,
         },
         {base_id: 71,
          coords: (7185, 1251),
          name: "Kyoto",
          active: True,
         },
         {base_id: 72,
          coords: (7179, 1259),
          name: "Osaka",
          active: False, # too close to Kyoto and Nagoya
         },
         {base_id: 73,
          coords: (7211, 1248),
          name: "Nagoya",
          active: False, # too close to Kyoto and Osaka
         },
         {base_id: 74,
          coords: (7275, 1236),
          name: "Tokyo",
          active: True,
         },
         {base_id: 75,
          coords: (7302, 1177),
          name: "Sendai",
          active: True,
         },
         {base_id: 76,
          coords: (7312, 1068),
          name: "Sapporo",
          active: True,
         },
         {base_id: 77,
          coords: (4988, 1557),
          name: "Jeddah",
          active: True,
         },
         {base_id: 78,
          coords: (4996, 1490),
          name: "Medina",
          active: False, # redacted
         },
         {base_id: 79,
          coords: (5001, 1560),
          name: "Mecca",
          active: False, # redacted
         },
         {base_id: 80,
          coords: (5159, 1486),
          name: "Riyadh",
          active: True,
         },
         {base_id: 81,
          coords: (5188, 1383),
          name: "Kuwait City",
          active: True,
         },
         {base_id: 82,
          coords: (5333, 1490),
          name: "Abu Dhabi",
          active: True,
         },
         {base_id: 83,
          coords: (5235, 1446),
          name: "Dammam",
          active: True,
         },
         {base_id: 84,
          coords: (5267, 1472),
          name: "Doha",
          active: True,
         },
         {base_id: 85,
          coords: (5754, 1613),
          name: "Mumbai",
          active: True,
         },
         {base_id: 86,
          coords: (6383, 1735),
          name: "Bangkok",
          active: True,
         },
         {base_id: 87,
          coords: (5882, 1652),
          name: "Hyderabad",
          active: True,
         },
         {base_id: 88,
          coords: (5921, 1750),
          name: "Chennai",
          active: True,
         },
         {base_id: 89,
          coords: (5861, 1752),
          name: "Bangalore",
          active: True,
         },
         {base_id: 90,
          coords: (6106, 1535),
          name: "Kolkata",
          active: True,
         },
         {base_id: 91,
          coords: (5851, 1396),
          name: "New Delhi",
          active: True,
         },
         {base_id: 92,
          coords: (7578, 2674),
          name: "Brisbane",
          active: True,
         },
         {base_id: 93,
          coords: (7532, 2818),
          name: "Sydney",
          active: True,
         },
         {base_id: 94,
          coords: (7488, 2852),
          name: "Canberra",
          active: True,
         },
         {base_id: 95,
          coords: (7397, 2908),
          name: "Melbourne",
          active: True,
         },
         {base_id: 96,
          coords: (7249, 2842),
          name: "Adelaide",
          active: True,
         },
         {base_id: 97,
          coords: (6733, 2775),
          name: "Perth",
          active: True,
         },
         {base_id: 98,
          coords: (7436, 2486),
          name: "Cairns",
          active: True,
         },
         {base_id: 99,
          coords: (7547, 2797),
          name: "Newcastle",
          active: False, # too close to Perth
         },
         {base_id: 100,
          coords: (7073, 2330),
          name: "Darwin",
          active: True,
         },
         {base_id: 101,
          coords: (8073, 2888),
          name: "Auckland",
          active: True,
         },
         {base_id: 102,
          coords: (8076, 2985),
          name: "Wellington",
          active: False, # base culling
         },
         {base_id: 103,
          coords: (8024, 3038),
          name: "Christchurch",
          active: False, # base culling
         },
         {base_id: 104,
          coords: (2289, 1053),
          name: "Toronto",
          active: True,
         },
         {base_id: 105,
          coords: (1884,  912),
          name: "Winnipeg",
          active: True,
         },
         {base_id: 106,
          coords: (1295,  927),
          name: "Vancouver",
          active: False, # too close to Seattle
         },
         {base_id: 107,
          coords: (1513,  828),
          name: "Edmonton",
          active: True,
         },
         {base_id: 108,
          coords: (2472,  981),
          name: "Quebec",
          active: True,
         },
         {base_id: 109,
          coords: (2420, 1010),
          name: "Montreal",
          active: True,
         },
         {base_id: 110,
          coords: (1312,  967),
          name: "Seattle",
          active: True,
         },
         {base_id: 111,
          coords: (1911, 1109),
          name: "Omaha",
          active: True,
         },
         {base_id: 112,
          coords: (1430, 1302),
          name: "San Diego",
          active: True,
         },
         {base_id: 113,
          coords: (1892, 1298),
          name: "Dallas",
          active: True,
         },
         {base_id: 114,
          coords: (2203, 1083),
          name: "Detroit",
          active: True,
         },
         {base_id: 115,
          coords: (2098, 1093),
          name: "Chicago",
          active: True,
         },
         {base_id: 116,
          coords: (1973, 1025),
          name: "Minneapolis",
          active: True,
         },
         {base_id: 117,
          coords: (1407, 1275),
          name: "Los Angeles",
          active: False, # too close to San Diego
         },
         {base_id: 118,
          coords: (1545, 1286),
          name: "Phoenix",
          active: True,
         },
         {base_id: 119,
          coords: (1550, 1122),
          name: "Salt Lake City",
          active: True,
         },
         {base_id: 120,
          coords: (2410, 1117),
          name: "New York",
          active: True,
         },
         {base_id: 121,
          coords: (2476, 1084),
          name: "Boston",
          active: True,
         },
         {base_id: 122,
          coords: (2177, 1279),
          name: "Atlanta",
          active: True,
         },
         {base_id: 123,
          coords: (2270, 1459),
          name: "Miami",
          active: True,
         },
         {base_id: 124,
          coords: (2211, 1406),
          name: "Clearwater",
          active: False, # redacted
         },
         {base_id: 125,
          coords: (2236, 1357),
          name: "Jacksonville",
          active: True,
         },
         {base_id: 126,
          coords: (1925, 1370),
          name: "Houston",
          active: True,
         },
         {base_id: 127,
          coords: (1704, 1144),
          name: "Denver",
          active: True,
         },
         {base_id: 128,
          coords: (1669, 1248),
          name: "Albuquerque",
          active: True,
         },
         {base_id: 129,
          coords: (2048, 1248),
          name: "Memphis",
          active: True,
         },
         {base_id: 130,
          coords: (2045, 1365),
          name: "New Orleans",
          active: True,
         },
         {base_id: 131,
          coords: (1839, 1606),
          name: "Mexico City",
          active: True,
         },
         {base_id: 132,
          coords: (1743, 1577),
          name: "Guadalajara",
          active: True,
         },
         {base_id: 133,
          coords: (2067, 1735),
          name: "San Salvador",
          active: True,
         },
         {base_id: 134,
          coords: (2035, 1715),
          name: "Guatemala",
          active: True,
         },
         {base_id: 135,
          coords: (2766, 2834),
          name: "Buenos Aires",
          active: True,
         },
         {base_id: 136,
          coords: (3035, 2586),
          name: "Sao Paolo",
          active: True,
         },
         {base_id: 137,
          coords: (2819, 2840),
          name: "Montevideo",
          active: False, # lacking significance, too close to Buenos Aires
         },
         {base_id: 138,
          coords: (3112, 2569),
          name: "Rio de Janeiro",
          active: True,
         },
         {base_id: 139,
          coords: (2342, 2321),
          name: "Lima",
          active: True,
         },
         {base_id: 140,
          coords: (2542, 3292),
          name: "Ushuaia",
          active: True,
         },
         {base_id: 141,
          coords: (2409, 1942),
          name: "Bogota",
          active: True,
         },
         {base_id: 142,
          coords: (2485, 2912),
          name: "Mar del Plata",
          active: True,
         },
         {base_id: 143,
          coords: (2729, 2117),
          name: "Manaus",
          active: True,
         },
         {base_id: 144,
          coords: (2487, 2808),
          name: "Santiago",
          active: True,
         },
         {base_id: 145,
          coords: (2453,  177),
          name: "Quttinirpaaq",
          active: True,
         },
         {base_id: 146,
          coords: (1331,  386),
          name: "Banks Island",
          active: True,
         },
         {base_id: 147,
          coords: (   0,    0),
          name: "North Pole",
          active: True,
         },
         {base_id: 148,
          coords: (6160,  202),
          name: "Schmidt Island",
          active: True,
         },
         {base_id: 149,
          coords: (8179,  427),
          name: "Wrangel Island",
          active: True,
         },
         {base_id: 150,
          coords: (7900, 3812),
          name: "Mount Erebus",
          active: True,
         },
         {base_id: 151,
          coords: (7259, 3641),
          name: "Terre Adelie",
          active: True,
         },
         {base_id: 152,
          coords: (4608, 3983),
          name: "Dronnig Maud",
          active: True,
         },
         {base_id: 153,
          coords: (3721, 1404),
          name: "Canary Islands",
          active: True,
         },
         {base_id: 154,
          coords: (3460, 1169),
          name: "Azores",
          active: True,
         },
         {base_id: 155,
          coords: (2621, 1311),
          name: "Bermuda",
          active: True,
         },
         {base_id: 156,
          coords: (3940,  634),
          name: "Faroe Islands",
          active: False, # base culling
         },
         {base_id: 157,
          coords: ( 505, 1563),
          name: "Honolulu",
          active: True,
         },
         {base_id: 158,
          coords: (3559, 1707),
          name: "Cape Verde",
          active: True,
         },
         {base_id: 159,
          coords: (3769, 2228),
          name: "Ascension Island",
          active: True,
         },
         {base_id: 160,
          coords: (3958, 2341),
          name: "Saint Helena",
          active: True,
         },
         {base_id: 161,
          coords: (2026, 2059),
          name: "Galapagos Islands",
          active: True,
         },
         {base_id: 162,
          coords: (8146, 2448),
          name: "Fiji",
          active: True,
         },
         {base_id: 163,
          coords: (7856, 2526),
          name: "New Caledonia",
          active: True,
         },
         {base_id: 164,
          coords: (7736, 2266),
          name: "Solomon Islands",
          active: True,
         },
         {base_id: 165,
          coords: (3000, 1300),
          name: "North Atlantic (underwater)",
          active: False, # Preliminary underwater base
         },
         {base_id: 166,
          coords: (3800, 2900),
          name: "South Atlantic (underwater)",
          active: False, # Preliminary underwater base
         },
         {base_id: 167,
          coords: (6000, 2600),
          name: "Indian Ocean (underwater)",
          active: False, # Preliminary underwater base
         },
         {base_id: 168,
          coords: (7900, 1600),
          name: "East Pacific (underwater)",
          active: False, # Preliminary underwater base
         },
         {base_id: 169,
          coords: (1600, 2800),
          name: "South Pacific (underwater)",
          active: False, # Preliminary underwater base
         },
         {base_id: 170,
          coords: ( 800, 1100),
          name: "North Pacific (underwater)",
          active: False, # Preliminary underwater base
         },
         {base_id: 171,
          coords: (3200, 1230),
          name: "Atlantis",
          active: False, # just kidding. ...or am I?
         },
         {base_id: 172,
          coords: (2242, 1240),
          name: "Lenoir", # Google DC
          active: True,
         },
         # More places:
         #   Anchorage
         #   Fairbanks
         #   Edinburgh
         #   Dharamsala (religion)
         #   Bodh Gaya (religion)
         #   Cadarache (ITER)
         #   Geneva (CERN)
         #   SPring-8
         #   Camp Williams (NSA Utah Data Center, Bluffdale, UT, United States)
         #   Fort Meade (NSA data center)
        ]

#bases_uv = [(float(u)/8192.0, 1.0-float(v)/4096.0) for u,v in bases_raw]
bases_uv = [(float(u)/8192.0, 1.0-float(v)/4096.0)
            for u,v in [b[coords] for b in bases if b[active]]]

